language: python
python:
 - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-dev python-pip libxslt1-dev libxml2-dev
install:
 - pip install lxml
 - sudo pip install --editable .
 - bikeshed update
script: bikeshed test
